apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
data:
  config.json: |
    {"tokens":{"AccessToken":"90dfe15b2460e591b34c5b3182ab70239e575edabb80ba4a0f04b8d5"}, "tags":{"Env":"k8s"}, "serverurl":"https://api.lacework.net"}